version: '3.9' # Docker Composeのバージョン

services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: dummy_secret_key
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      bash -c "
        if [ \"$RAILS_ENV\" = \"production\" ]; then
          bundle exec rails assets:precompile &&
          bin/rails server -b 0.0.0.0
        else
          bin/rails server -b 0.0.0.0
        fi
      "
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
